# Generated by Django 5.1.7 on 2025-03-31 13:31

import policy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                ("requirer", models.UUIDField(primary_key=True, serialize=False)),
                ("domains", models.JSONField()),
                ("auth", models.JSONField()),
                ("src_ips", policy.models.IpSetField()),
                ("implicit_src_ips", models.BooleanField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                            ("pending", "pending"),
                        ],
                        db_index=True,
                    ),
                ),
                ("accepted_auth", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("requirer", models.UUIDField(db_index=True, null=True)),
                ("domains", models.JSONField(default=list)),
                ("auth", models.JSONField(default=list)),
                ("src_ips", policy.models.IpSetField(default=list)),
                (
                    "verdict",
                    models.TextField(
                        choices=[
                            (policy.models.Verdict["ACCEPT"], policy.models.Verdict["ACCEPT"]),
                            (policy.models.Verdict["REJECT"], policy.models.Verdict["REJECT"]),
                        ]
                    ),
                ),
                ("comment", models.TextField(default="")),
            ],
        ),
    ]
