name: Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  docs-checks:
    uses: canonical/operator-workflows/.github/workflows/docs.yaml@main
    runs-on: 'ubuntu-22.04'
    secrets: inherit
    with:
      vale-files: './**/*.md'
      linkcheck-files: './**/*.md'
