name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-to-edge:
    strategy:
      matrix:
        charm: [ squid-forward-proxy, http-proxy-policy ]
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@main
    secrets: inherit
    with:
      channel: latest/edge
      identifier: ${{ matrix.charm }}
      working-directory: './${{ matrix.charm }}-operator'
